version: '3.8'

services:
  # Service Aplikasi Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - "DB_HOST=db"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      # Variabel lain dari file .env Anda akan ditambahkan di Portainer UI
      - "APP_KEY=${APP_KEY}"
      - "APP_ENV=${APP_ENV}"
      - "APP_DEBUG=${APP_DEBUG}"
      - "APP_URL=${APP_URL}"
    networks:
      - laravel-net

  # Service Web Server Nginx
  nginx:
    image: nginx:1.23-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8004:80" # Akses aplikasi dari luar melalui port 8000
    volumes:
      - .:/var/www/html
      # PERUBAHAN: Mount seluruh direktori konfigurasi, bukan hanya satu file.
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel-net

  # Service Database (contoh: MySQL)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  db-data:
    driver: local
