version: "3.8"

configs:
  nginx_conf:
    file: ./nginx.conf

services:
  db:
    image: mysql:8.0
    # konfigurasi db ...

  app:
    image: aarcsti/cctv-miot-app:latest
    working_dir: /var/www/html
    environment:
      # variabel environment ...
    volumes:
      - app-code:/var/www/html          # ⇐ volume berbagi kode
      - laravel-storage:/var/www/html/storage
      - laravel-bootstrap-cache:/var/www/html/bootstrap/cache
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - app-code:/var/www/html:ro       # ⇐ volume berbagi kode (read-only)
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # konfigurasi phpMyAdmin ...

networks:
  laravel-net:
    driver: overlay
    attachable: true

volumes:
  db-data:
  laravel-storage:
  laravel-bootstrap-cache:
  app-code:                             # ⇐ definisi volume baru
