# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    # --- PERUBAHAN DI SINI ---
    # Hapus volume mount untuk kode. Kode sekarang ada di dalam image.
    # volumes:
    #   - ./:/var/www/html
    env_file:
      - .env.docker
    networks:
      - laravel-network
    depends_on: # Tambahkan ini agar app menunggu db
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html # Volume ini tetap ada untuk Nginx agar bisa mengakses file public
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel-network

  # Layanan phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      # Gunakan variabel dari .env.docker
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - laravel-network

# Mendefinisikan jaringan untuk komunikasi antar-container
networks:
  laravel-network:
    driver: bridge

# Mendefinisikan volume untuk persistensi data database
volumes:
  db-data:
    driver: local
