# docker-compose.yml
# File ini mendefinisikan dan mengonfigurasi semua layanan yang dibutuhkan aplikasi Anda.

version: '3.8'

services:
  # Layanan Aplikasi Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    # --- PERUBAHAN DI SINI ---
    # Memberitahu Docker Compose untuk memuat variabel dari file .env.docker
    # dan menyuntikkannya ke dalam kontainer ini.
    env_file:
      - .env.docker
    networks:
      - laravel-network

  # Layanan Database MySQL
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    # Variabel environment untuk database juga diambil dari .env.docker
    env_file:
      - .env.docker
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  # Layanan Web Server Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel-network

  # Layanan phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      # Gunakan variabel dari .env.docker
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - laravel-network

# Mendefinisikan jaringan untuk komunikasi antar-container
networks:
  laravel-network:
    driver: bridge

# Mendefinisikan volume untuk persistensi data database
volumes:
  db-data:
    driver: local
