# docker-compose.yml
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:JATe/JyiyMJmL26D/TQ26lfU/1bUlakRsPmXWDv761k=
      APP_URL: http://localhost
      DB_HOST: db
      DB_DATABASE: cctv_miot
      DB_USERNAME: miot
      DB_PASSWORD: GantiPasswordUserKuat!
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./storage/app/public:/var/www/html/storage/app/public
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cctv_miot
      MYSQL_USER: miot
      MYSQL_PASSWORD: GantiPasswordUserKuat!
      MYSQL_ROOT_PASSWORD: GantiPasswordRootKuat!
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - laravel

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    networks:
      - laravel

networks:
  laravel:

volumes:
  db-data:
