version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: cctv_miot
      MYSQL_USER: miot
      MYSQL_PASSWORD: "GantiPasswordUserKuat!"
      MYSQL_ROOT_PASSWORD: "GantiPasswordRootKuat!"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-net
    # depends_on di Swarm tidak efektif; gunakan healthcheck + retry di app

  app:
    image: aarcsti/cctv-miot-app:latest
    working_dir: /var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: cctv_miot
      DB_USERNAME: miot
      DB_PASSWORD: "GantiPasswordUserKuat!"
    volumes:
      - laravel-storage:/var/www/html/storage
      - laravel-bootstrap-cache:/var/www/html/bootstrap/cache
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # kalau perlu: - ./src:/var/www/html:ro
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: "3306"
      PMA_USER: miot
      PMA_PASSWORD: "GantiPasswordUserKuat!"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: overlay
    attachable: true

volumes:
  db-data:
  laravel-storage:
  laravel-bootstrap-cache:
