<?php
// Variables
return [
  "creatorName" => "Ahmad Akmal Rijal",
  "creatorUrl" => "https://ahmadakmal.com",
  "templateName" => "MiotVision",
  "templateSuffix" => "Bootstrap Admin Template",
  "templateVersion" => "2.0.0",
  "templateFree" => false,
  "templateDescription" => "",
  "templateKeyword" => "",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "moreThemes" => "",
  "documentation" => "",
  "generator" => "",
  "changelog" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "",
  "logoUrl" => "assets/img/favicon/icon_cctv_miot.png",
];
