# .github/workflows/deploy.yml (Versi dengan Build & Push)
name: Build, Push, and Deploy to Portainer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Konteks build adalah root proyek
          file: ./app/Dockerfile # Path ke Dockerfile Anda
          push: true
          # Ganti 'your-dockerhub-username/your-app-name' dengan nama image Anda
          tags: AARCSTI20/cctv-miot-app:latest

      - name: Trigger Portainer Webhook
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
