# .github/workflows/deploy.yml
# Alur kerja ini akan otomatis membangun, mem-push image, dan men-deploy ulang stack Anda.

name: Deploy to Portainer

on:
  push:
    branches:
      - main # Atur branch pemicu di sini

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Login ke Docker Hub (atau registry lain)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Langkah 3: Build dan Push Docker image ke registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cctv-miot:latest # Ganti dengan nama image Anda

      # Langkah 4: Trigger Portainer webhook untuk redeploy stack
      - name: Trigger Portainer Redeploy
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
