# .github/workflows/deploy.yml
name: Trigger Portainer Redeploy

on:
  push:
    branches:
      - main # Atur branch pemicu di sini

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portainer Redeploy Webhook
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
